# Generated by Django 3.2.3 on 2021-05-30 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('commission', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('income', models.IntegerField()),
                ('address', models.CharField(max_length=1000)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loanapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='NEW', max_length=200)),
                ('interest_rate', models.IntegerField()),
                ('date_given', models.DateField(auto_now_add=True)),
                ('till_date_given', models.DateField(auto_now_add=True)),
                ('amount_given', models.IntegerField()),
                ('tenure', models.IntegerField()),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='loanapp.agent')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='loanapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=1000)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='loanapp.customer')),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='loanapp.loan')),
            ],
        ),
    ]
