# Generated by Django 3.2.3 on 2021-06-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0001_initial'),
    ]

    operations = [
      
      
    ]
