# Generated by Django 3.2.3 on 2021-05-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0003_auto_20210530_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='user',
        ),
        migrations.AddField(
            model_name='agent',
            name='name',
            field=models.CharField(default='pawan', max_length=50),
            preserve_default=False,
        ),
    ]
