# Generated by Django 3.2.3 on 2021-05-30 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loanapp', '0004_auto_20210530_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='name',
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
