# Generated by Django 3.2.3 on 2021-05-30 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loanapp', '0005_auto_20210530_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
