# Generated by Django 3.2.3 on 2021-05-30 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0006_auto_20210530_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='amount_given',
            new_name='loan_amount',
        ),
    ]
