# Generated by Django 3.2.3 on 2021-05-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0007_rename_amount_given_loan_loan_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='tenure',
            new_name='tenure_in_months',
        ),
    ]
