# Generated by Django 3.2.3 on 2021-05-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0008_rename_tenure_loan_tenure_in_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
