# Generated by Django 3.2.3 on 2021-05-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0009_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account',
        ),
        migrations.AddField(
            model_name='customer',
            name='account_number',
            field=models.IntegerField(default=123123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
