# Generated by Django 3.2.3 on 2021-05-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0011_auto_20210530_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='date_given',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='till_date_given',
        ),
    ]
