# Generated by Django 3.2.3 on 2021-05-30 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0013_auto_20210530_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='date_given',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='till_date_given',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
