# Generated by Django 3.2.3 on 2021-05-30 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0014_auto_20210530_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_given',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='till_date_given',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
